server:
  port: 8087

spring:
  profiles:
    active: dev
  redis:
    port: 6379
    host: localhost
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5
        max-wait: 3000
    ssl: false
    timeout: 3000
    database: 2
  cache:
    type: redis

framework:
  config:
    redis:
      enable: true
    mysql:
      slave: true
    activiti:
      enable: false
    dubbo:
      enable: true
    rabbit:
      enable: false
    mongo:
      enable: true
    swagger:
      enable: true
      scan-package: com.magic.platform
#      filters: stat,config