server:
  port: 8087

spring:
  profiles:
    active: dev
  redis:
    port: 6379
    host: localhost
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
    ssl: false
    timeout: 3000

framework:
  config:
    mysql:
      slave: true
    activiti:
      enable: false
    dubbo:
      enable: true
    rabbit:
      enable: false
    mongo:
      enable: true
    swagger:
      enable: true
      scan-package: com.magic.platform
#      filters: stat,config