server:
  port: 8087

spring:
  profiles:
    active: dev

framework:
  config:
    redis:
      enable: true
    mysql:
      slave: true
    activiti:
      enable: false
    dubbo:
      enable: true
    rabbit:
      enable: false
    mongo:
      enable: true
    swagger:
      enable: true
      scan-package: com.magic.platform
#      filters: stat,config